
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuckksomhlmfoccnmhae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1Y2trc29taGxtZm9jY25taGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NjU0NDgsImV4cCI6MjA1ODE0MTQ0OH0.gwH-hoH8_olm7tbBBcPVmGU1njQXgQST8LqYePfaV74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
