
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oupvxtnxdprsmlvxpwmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91cHZ4dG54ZHByc21sdnhwd21pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzU1NjYsImV4cCI6MjA1OTI1MTU2Nn0.ZBwD8BtbAiIgq7Izd04V-dEY8jfbMa5Pe_zovfMWq9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
